"use client";
import { useEffect, useRef, useState } from "react";
import { Camera, Cat, ChevronRight, FileAudio, HeartPulse, History, ImagePlus, Info, LoaderCircle, MessageCircleQuestion, PawPrint, Plus, ShieldAlert, Sparkles, ThumbsDown, ThumbsUp, Upload, UserRound } from "lucide-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";

type CatProfile = { id: string; name: string; breed: string; age: string; notes: string };
type Result = { intention: { label: string; confidence: number; evidence: string[] }; emotion: { label: string; confidence: number; evidence: string[] }; health: { level: string; observations: string[] }; summary: string; recommendations: string[]; disclaimer: string };
type Report = { id: string; catName: string; mediaType: string; fileName: string; mode: string; summary: string; result: Result; createdAt: string };
const mediaLabels: Record<string, string> = { image: "图片", video: "视频", audio: "音频" };

async function makePreview(file: File) {
  if (file.type.startsWith("image/")) return await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file); });
  if (file.type.startsWith("video/")) return await new Promise<string>((resolve) => { const video = document.createElement("video"); const url = URL.createObjectURL(file); video.src = url; video.muted = true; video.playsInline = true; video.onloadeddata = () => { video.currentTime = Math.min(0.5, video.duration / 2); }; video.onseeked = () => { const canvas = document.createElement("canvas"); canvas.width = Math.min(video.videoWidth, 1000); canvas.height = Math.round(canvas.width * video.videoHeight / video.videoWidth); canvas.getContext("2d")?.drawImage(video, 0, 0, canvas.width, canvas.height); URL.revokeObjectURL(url); resolve(canvas.toDataURL("image/jpeg", 0.82)); }; video.onerror = () => { URL.revokeObjectURL(url); resolve(""); }; });
  return "";
}
async function readAudioFeatures(file: File) {
  if (!file.type.startsWith("audio/") && !file.type.startsWith("video/")) return "无音频特征";
  try { const buffer = await file.arrayBuffer(); const ctx = new AudioContext(); const audio = await ctx.decodeAudioData(buffer.slice(0)); const data = audio.getChannelData(0); const step = Math.max(1, Math.floor(data.length / 12000)); let sum = 0, peaks = 0, last = 0; for (let i = 0; i < data.length; i += step) { const v = data[i]; sum += v * v; if (Math.abs(v) > .35 && Math.abs(last) <= .35) peaks++; last = v; } await ctx.close(); const rms = Math.sqrt(sum / Math.ceil(data.length / step)); return `时长约 ${audio.duration.toFixed(1)} 秒；平均强度 ${rms > .16 ? "较高" : rms > .06 ? "中等" : "较低"}；明显声学峰值约 ${peaks} 次。该特征不等于叫声含义。`; } catch { return "浏览器无法解码此文件的音频轨道"; }
}

export default function Home() {
  const [tab, setTab] = useState("analyze"), [mode, setMode] = useState("demo");
  const [cats, setCats] = useState<CatProfile[]>([]), [reports, setReports] = useState<Report[]>([]);
  const [file, setFile] = useState<File | null>(null), [preview, setPreview] = useState(""), [features, setFeatures] = useState("");
  const [catId, setCatId] = useState(""), [context, setContext] = useState(""), [loading, setLoading] = useState(false), [error, setError] = useState("");
  const [result, setResult] = useState<Result | null>(null), [reportId, setReportId] = useState(""), [feedback, setFeedback] = useState("");
  const inputRef = useRef<HTMLInputElement>(null);
  const refresh = async () => { const [c, r, s] = await Promise.all([fetch("/api/cats").then(x => x.json() as Promise<{ cats?: CatProfile[] }>).catch(() => ({ cats: [] })), fetch("/api/reports").then(x => x.json() as Promise<{ reports?: Report[] }>).catch(() => ({ reports: [] })), fetch("/api/status").then(x => x.json() as Promise<{ mode?: string }>).catch(() => ({ mode: "demo" }))]); setCats(c.cats || []); setReports(r.reports || []); setMode(s.mode || "demo"); };
  useEffect(() => { refresh(); }, []);
  useEffect(() => {
    const modelContext = (document as Document & { modelContext?: { registerTool: (tool: Record<string, unknown>, options?: { signal?: AbortSignal }) => void | Promise<void> } }).modelContext;
    if (!modelContext?.registerTool) return;
    const lifecycle = new AbortController();
    Promise.resolve(modelContext.registerTool({
      name: "start_cat_observation", title: "开始猫咪观察",
      description: "打开素材观察页，预填当时的场景，并可关联已有猫咪档案。用户仍需亲自选择要上传的图片、视频或音频。",
      inputSchema: { type: "object", properties: { context: { type: "string", description: "猫咪当时所处的场景" }, catName: { type: "string", description: "已有猫咪档案的名字" } }, additionalProperties: false },
      annotations: { readOnlyHint: false, untrustedContentHint: false },
      execute: async (input: unknown) => { const value = (input && typeof input === "object" ? input : {}) as { context?: string; catName?: string }; setTab("analyze"); if (value.context) setContext(value.context); const cat = cats.find(item => item.name === value.catName); if (cat) setCatId(cat.id); return { status: "ready", linkedCat: cat?.name || null, next: "请选择猫咪素材后生成报告" }; }
    }, { signal: lifecycle.signal })).catch(() => undefined);
    return () => lifecycle.abort();
  }, [cats]);
  const chooseFile = async (next: File) => { setError(""); setResult(null); setFile(next); setPreview(await makePreview(next)); setFeatures(await readAudioFeatures(next)); };
  const analyze = async () => { if (!file) return setError("请先选择一段图片、视频或音频"); setLoading(true); setError(""); try { const form = new FormData(); const cat = cats.find(c => c.id === catId); form.append("file", file); form.append("catId", catId); form.append("catName", cat?.name || "未命名猫咪"); form.append("context", context); form.append("features", features); form.append("preview", preview); const response = await fetch("/api/analyze", { method: "POST", body: form }); const data = await response.json() as { error?: string; result: Result; mode: string; reportId: string }; if (!response.ok) throw new Error(data.error || "分析失败"); setResult(data.result); setMode(data.mode); setReportId(data.reportId); await refresh(); setTimeout(() => document.getElementById("report")?.scrollIntoView({ behavior: "smooth", block: "start" }), 100); } catch (e) { setError(e instanceof Error ? e.message : "分析失败"); } finally { setLoading(false); } };
  const sendFeedback = async (helpful: boolean) => { if (!reportId || feedback) return; await fetch("/api/feedback", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ reportId, helpful }) }); setFeedback(helpful ? "感谢，你认为这份观察有帮助" : "谢谢反馈，我们会改进观察结果"); };
  return <main className="app-shell">
    <header className="topbar"><button className="brand" onClick={() => setTab("analyze")}><span className="brand-mark"><PawPrint size={21}/></span><span>喵懂 <b>AI</b></span></button><div className={`mode-pill ${mode}`}><i/>{mode === "live" ? "AI 实时分析" : "演示模式"}</div></header>
    <Tabs value={tab} onValueChange={setTab} className="workspace">
      <TabsContent value="analyze" className="main-content">
        <section className="intro-grid"><div className="intro-copy"><p className="eyebrow">观察，而不是武断翻译</p><h1>听懂线索，<br/><em>看见状态。</em></h1><p>上传一段猫咪素材，结合声音、姿态和场景，获得更谨慎的行为观察。</p><div className="trust-row"><span><ShieldAlert size={16}/>非疾病诊断</span><span><MessageCircleQuestion size={16}/>非准确猫语翻译</span></div></div><div className="hero-art"><img src="/cat-observer.png" alt="一只正在被温和观察的猫咪插画"/><div className="sound-chip"><span/><span/><span/><span/><span/><b>正在倾听</b></div></div></section>
        <section className="analyze-card"><div className="section-title"><div><span>01</span><h2>添加观察素材</h2></div><p>支持常见图片、视频、音频，最大 30MB</p></div>
          <button className={`dropzone ${file ? "has-file" : ""}`} onClick={() => inputRef.current?.click()} onDrop={e => { e.preventDefault(); const f = e.dataTransfer.files[0]; if (f) chooseFile(f); }} onDragOver={e => e.preventDefault()}><input ref={inputRef} hidden type="file" accept="image/*,video/*,audio/*" onChange={e => e.target.files?.[0] && chooseFile(e.target.files[0])}/>{file ? <><div className="preview-wrap">{preview ? <img src={preview} alt="已选素材预览"/> : <FileAudio size={42}/>}<span className="file-badge">{mediaLabels[file.type.split("/")[0]] || "素材"}</span></div><div className="file-info"><strong>{file.name}</strong><span>{(file.size / 1024 / 1024).toFixed(1)} MB · 点击更换</span></div></> : <><span className="upload-icon"><Upload size={28}/></span><strong>拍摄或选择猫咪素材</strong><span>也可以把文件拖到这里</span><div className="media-types"><i><ImagePlus size={17}/>图片</i><i><Camera size={17}/>视频</i><i><FileAudio size={17}/>音频</i></div></>}</button>
          <div className="form-grid"><label>关联猫咪<select value={catId} onChange={e => setCatId(e.target.value)}><option value="">暂不关联</option>{cats.map(cat => <option key={cat.id} value={cat.id}>{cat.name}</option>)}</select></label><label>当时发生了什么？<textarea value={context} onChange={e => setContext(e.target.value)} placeholder="例如：晚上 11 点，在食盆旁连续叫，刚吃过晚饭…"/></label></div>{error && <p className="error"><Info size={16}/>{error}</p>}<button className="analyze-btn" disabled={!file || loading} onClick={analyze}>{loading ? <><LoaderCircle className="spin" size={19}/>正在观察素材…</> : <><Sparkles size={19}/>生成综合观察报告<ChevronRight size={19}/></>}</button>
        </section>
        {result && <section id="report" className="report-card"><div className="report-head"><div><p className="eyebrow">综合观察报告</p><h2>{cats.find(c => c.id === catId)?.name || "这只猫咪"}现在可能怎么了？</h2></div><span className={`mode-tag ${mode}`}>{mode === "live" ? "AI 分析" : "演示结果"}</span></div><p className="report-summary">{result.summary}</p><div className="result-grid"><ResultBlock icon={<MessageCircleQuestion/>} tone="coral" label="声音意图推测" title={result.intention.label} confidence={result.intention.confidence} items={result.intention.evidence}/><ResultBlock icon={<Cat/>} tone="blue" label="情绪状态观察" title={result.emotion.label} confidence={result.emotion.confidence} items={result.emotion.evidence}/><ResultBlock icon={<HeartPulse/>} tone="amber" label="可见健康异常" title={result.health.level} items={result.health.observations}/></div><div className="recommend"><h3>接下来可以这样做</h3>{result.recommendations.map((x, i) => <p key={x}><b>{String(i + 1).padStart(2, "0")}</b>{x}</p>)}</div><div className="disclaimer"><ShieldAlert size={20}/><p><strong>重要说明</strong>{result.disclaimer}</p></div><div className="feedback"><span>{feedback || "这份观察对你有帮助吗？"}</span>{!feedback && <div><button aria-label="有帮助" onClick={() => sendFeedback(true)}><ThumbsUp size={17}/></button><button aria-label="没帮助" onClick={() => sendFeedback(false)}><ThumbsDown size={17}/></button></div>}</div></section>}
      </TabsContent>
      <TabsContent value="profiles" className="main-content secondary-page"><div className="page-heading"><div><p className="eyebrow">长期观察更有价值</p><h1>猫咪档案</h1><p>记录个体差异，帮助你对照每只猫自己的日常基线。</p></div><AddCatDialog onSaved={refresh}/></div><div className="profile-grid">{cats.length ? cats.map(cat => <article className="profile-card" key={cat.id}><span><Cat/></span><div><h3>{cat.name}</h3><p>{cat.breed} · {cat.age}</p><small>{cat.notes || "暂时没有补充备注"}</small></div></article>) : <Empty icon={<UserRound/>} title="还没有猫咪档案" text="先添加第一只猫，之后的报告就能按猫咪归档。"/>}</div></TabsContent>
      <TabsContent value="history" className="main-content secondary-page"><div className="page-heading"><div><p className="eyebrow">变化比单次结果更重要</p><h1>观察记录</h1><p>按时间回看情绪、声音和可见状态的变化。</p></div></div><div className="history-list">{reports.length ? reports.map(r => <article key={r.id}><span className="history-icon">{r.mediaType.startsWith("audio") ? <FileAudio/> : r.mediaType.startsWith("video") ? <Camera/> : <ImagePlus/>}</span><div><small>{new Date(r.createdAt).toLocaleString("zh-CN")}</small><h3>{r.catName} · {r.fileName}</h3><p>{r.summary}</p></div><span className={`mode-tag ${r.mode}`}>{r.mode === "live" ? "AI" : "演示"}</span></article>) : <Empty icon={<History/>} title="还没有观察记录" text="完成第一次素材分析后，报告会出现在这里。"/>}</div></TabsContent>
      <TabsList className="bottom-nav"><TabsTrigger value="analyze"><Sparkles/><span>观察</span></TabsTrigger><TabsTrigger value="profiles"><Cat/><span>猫咪</span></TabsTrigger><TabsTrigger value="history"><History/><span>记录</span></TabsTrigger></TabsList>
    </Tabs><footer>喵懂 AI 只提供行为与可见状态观察，不替代专业兽医诊疗。</footer>
  </main>;
}
function ResultBlock({ icon, tone, label, title, confidence, items }: { icon: React.ReactNode; tone: string; label: string; title: string; confidence?: number; items: string[] }) { return <article><span className={`result-icon ${tone}`}>{icon}</span><small>{label}</small><h3>{title}</h3>{typeof confidence === "number" && <div className="confidence"><i style={{ width: `${confidence}%` }}/><span>{confidence}% 线索匹配</span></div>}<ul>{items.map(x => <li key={x}>{x}</li>)}</ul></article>; }
function Empty({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="empty"><span>{icon}</span><h3>{title}</h3><p>{text}</p></div>; }
function AddCatDialog({ onSaved }: { onSaved: () => void }) { const [open, setOpen] = useState(false), [form, setForm] = useState({ name: "", breed: "", age: "", notes: "" }), [saving, setSaving] = useState(false); const save = async () => { if (!form.name.trim()) return; setSaving(true); const response = await fetch("/api/cats", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); setSaving(false); if (response.ok) { setOpen(false); setForm({ name: "", breed: "", age: "", notes: "" }); onSaved(); } }; return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><button className="add-btn"><Plus size={18}/>添加猫咪</button></DialogTrigger><DialogContent className="cat-dialog"><DialogHeader><DialogTitle>添加猫咪档案</DialogTitle></DialogHeader><label>名字<input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="例如：年糕"/></label><div className="dialog-row"><label>品种<input value={form.breed} onChange={e => setForm({ ...form, breed: e.target.value })} placeholder="例如：英短"/></label><label>年龄<input value={form.age} onChange={e => setForm({ ...form, age: e.target.value })} placeholder="例如：3 岁"/></label></div><label>日常与病史备注<textarea value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })} placeholder="性格、长期用药、已知问题等"/></label><button className="analyze-btn" onClick={save} disabled={saving || !form.name.trim()}>{saving ? "保存中…" : "保存档案"}</button></DialogContent></Dialog>; }
